/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as EntrenarRouteImport } from './routes/entrenar'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as AprenderIndexRouteImport } from './routes/aprender.index'
import { Route as AprenderLessonIdRouteImport } from './routes/aprender.$lessonId'
import { Route as EntrenarIndexRouteImport } from './routes/entrenar.index'
import { Route as EntrenarWorkoutIdRouteImport } from './routes/entrenar.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenarRoute = EntrenarRouteImport.update({
  id: '/entrenar',
  path: '/entrenar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderIndexRoute = AprenderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AprenderRoute,
} as any)
const AprenderLessonIdRoute = AprenderLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AprenderRoute,
} as any)
const EntrenarIndexRoute = EntrenarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntrenarRoute,
} as any)
const EntrenarWorkoutIdRoute = EntrenarWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => EntrenarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRouteWithChildren
  '/entrenar': typeof EntrenarRouteWithChildren
  '/progreso': typeof ProgresoRoute
  '/aprender/$lessonId': typeof AprenderLessonIdRoute
  '/entrenar/$workoutId': typeof EntrenarWorkoutIdRoute
  '/aprender/': typeof AprenderIndexRoute
  '/entrenar/': typeof EntrenarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progreso': typeof ProgresoRoute
  '/aprender/$lessonId': typeof AprenderLessonIdRoute
  '/entrenar/$workoutId': typeof EntrenarWorkoutIdRoute
  '/aprender': typeof AprenderIndexRoute
  '/entrenar': typeof EntrenarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRouteWithChildren
  '/entrenar': typeof EntrenarRouteWithChildren
  '/progreso': typeof ProgresoRoute
  '/aprender/$lessonId': typeof AprenderLessonIdRoute
  '/entrenar/$workoutId': typeof EntrenarWorkoutIdRoute
  '/aprender/': typeof AprenderIndexRoute
  '/entrenar/': typeof EntrenarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/entrenar'
    | '/progreso'
    | '/aprender/$lessonId'
    | '/entrenar/$workoutId'
    | '/aprender/'
    | '/entrenar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progreso'
    | '/aprender/$lessonId'
    | '/entrenar/$workoutId'
    | '/aprender'
    | '/entrenar'
  id:
    | '__root__'
    | '/'
    | '/aprender'
    | '/entrenar'
    | '/progreso'
    | '/aprender/$lessonId'
    | '/entrenar/$workoutId'
    | '/aprender/'
    | '/entrenar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprenderRoute: typeof AprenderRouteWithChildren
  EntrenarRoute: typeof EntrenarRouteWithChildren
  ProgresoRoute: typeof ProgresoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenar': {
      id: '/entrenar'
      path: '/entrenar'
      fullPath: '/entrenar'
      preLoaderRoute: typeof EntrenarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender/': {
      id: '/aprender/'
      path: '/'
      fullPath: '/aprender/'
      preLoaderRoute: typeof AprenderIndexRouteImport
      parentRoute: typeof AprenderRoute
    }
    '/aprender/$lessonId': {
      id: '/aprender/$lessonId'
      path: '/$lessonId'
      fullPath: '/aprender/$lessonId'
      preLoaderRoute: typeof AprenderLessonIdRouteImport
      parentRoute: typeof AprenderRoute
    }
    '/entrenar/': {
      id: '/entrenar/'
      path: '/'
      fullPath: '/entrenar/'
      preLoaderRoute: typeof EntrenarIndexRouteImport
      parentRoute: typeof EntrenarRoute
    }
    '/entrenar/$workoutId': {
      id: '/entrenar/$workoutId'
      path: '/$workoutId'
      fullPath: '/entrenar/$workoutId'
      preLoaderRoute: typeof EntrenarWorkoutIdRouteImport
      parentRoute: typeof EntrenarRoute
    }
  }
}

interface AprenderRouteChildren {
  AprenderLessonIdRoute: typeof AprenderLessonIdRoute
  AprenderIndexRoute: typeof AprenderIndexRoute
}

const AprenderRouteChildren: AprenderRouteChildren = {
  AprenderLessonIdRoute: AprenderLessonIdRoute,
  AprenderIndexRoute: AprenderIndexRoute,
}

const AprenderRouteWithChildren = AprenderRoute._addFileChildren(
  AprenderRouteChildren,
)

interface EntrenarRouteChildren {
  EntrenarWorkoutIdRoute: typeof EntrenarWorkoutIdRoute
  EntrenarIndexRoute: typeof EntrenarIndexRoute
}

const EntrenarRouteChildren: EntrenarRouteChildren = {
  EntrenarWorkoutIdRoute: EntrenarWorkoutIdRoute,
  EntrenarIndexRoute: EntrenarIndexRoute,
}

const EntrenarRouteWithChildren = EntrenarRoute._addFileChildren(
  EntrenarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprenderRoute: AprenderRouteWithChildren,
  EntrenarRoute: EntrenarRouteWithChildren,
  ProgresoRoute: ProgresoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
